insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 1,'Eula','Lane','eula.lane@jigrormo.ye','(762) 526-5961','1955-04-06','Insurance Clerk')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 2,'Barry','Rodriquez','barry.rodriquez@zun.mm','(267) 955-5124','2014-04-06','Mortarman')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 3,'Eugenia','Selvi','eugenia.selvi@capfad.vn','(680) 368-2192','1974-03-22','Beer Coil Cleaner')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 4,'Alejandro','Miles','alejandro.miles@dec.bn','(281) 301-2039','2014-05-09','Scale Attendant')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 5,'Cora','Tesi','cora.tesi@bivo.yt','(600) 616-7955','1972-07-06','Clinical Audiologist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 6,'Marguerite','Ishii','marguerite.ishii@judbilo.gn','(882) 813-1374','1938-04-03','Parking Meter Collector')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 7,'Mildred','Jacobs','mildred.jacobs@joraf.wf','(642) 665-1763','1967-11-06','Business Unit Manager')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 8,'Gene','Goodman','gene.goodman@kem.tl','(383) 458-2132','2010-09-16','Technical Communicator')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 9,'Lettie','Bennett','lettie.bennett@odeter.bb','(769) 335-6771','1959-11-21','Correctional Officer Sergeant')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 10,'Mabel','Leach','mabel.leach@lisohuje.vi','(803) 586-8035','1946-10-28','Food Chemist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 11,'Jordan','Miccinesi','jordan.miccinesi@duod.gy','(531) 919-2280','1982-12-09','Signals Intelligence/Electronic Warfare Chief')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 12,'Marie','Parkes','marie.parkes@nowufpus.ph','(814) 667-8937','1943-10-10','Language Pathologist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 13,'Rose','Gray','rose.gray@kagu.hr','(713) 311-8766','1958-10-09','Wildlife Officer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 14,'Garrett','Stokes','garrett.stokes@fef.bg','(381) 421-2371','2009-07-20','Bindery Machine Operator')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 15,'Barbara','Matthieu','barbara.matthieu@derwogi.jm','(940) 463-7299','1930-07-16','Instructional Aide')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 16,'Jean','Rhodes','jean.rhodes@wehovuce.gu','(777) 435-9570','1949-12-23','Clinical Psychiatrist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 17,'Jack','Romoli','jack.romoli@zamum.bw','(517) 393-9630','1975-10-19','Mortician Investigator')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 18,'Pearl','Holden','pearl.holden@dunebuh.cr','(711) 904-3669','1950-02-13','Rod Buster Helper')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 19,'Belle','Montero','belle.montero@repiwid.si','(935) 404-4792','1933-03-08','Classroom Aide')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 20,'Olive','Molina','olive.molina@razuppa.ga','(935) 267-8492','1934-09-18','Traditional Chinese Herbalist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 21,'Minerva','Todd','minerva.todd@kulmenim.ad','(763) 948-4815','1951-02-19','Electronic Drafter')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 22,'Bobby','Pearson','bobby.pearson@ib.kg','(238) 240-2561','2015-07-14','Vault Teller')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 23,'Larry','Ciappi','larry.ciappi@ba.lk','(410) 257-1723','1996-07-29','Fire Sprinkler Installer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 24,'Ronnie','Salucci','ronnie.salucci@tohhij.lv','(566) 726-3346','1975-01-31','Brewery Pumper')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 25,'Walter','Grossi','walter.grossi@tuvo.sa','(416) 906-7221','1988-03-20','Kitchen Chef')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 26,'Frances','Koopmans','frances.koopmans@foga.tw','(611) 712-1562','1967-05-12','Medical Esthetician')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 27,'Frances','Fujimoto','frances.fujimoto@uswuzzub.jp','(919) 887-8542','1936-10-15','Auto Tire Worker')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 28,'Olivia','Vidal','olivia.vidal@hivwerip.vc','(982) 684-7650','1934-01-23','Semi-Truck Driver')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 29,'Edna','Henry','edna.henry@gugusu.rw','(811) 931-8202','1947-12-07','Command And Control')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 30,'Lydia','Brun','lydia.brun@zedekak.md','(927) 400-3928','1930-01-19','Drywall Hanger')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 31,'Jay','Blake','jay.blake@ral.mk','(365) 345-1498','2010-02-06','Real Property Evaluator')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 32,'Isabel','Serafini','isabel.serafini@turuhu.bh','(656) 968-9869','1974-02-14','Human Performance Professor')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 33,'Rebecca','Carter','rebecca.carter@omjo.et','(739) 612-6585','1959-09-03','V/Stol Landing Signal Officer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 34,'Maurice','Fabbrini','maurice.fabbrini@rig.bh','(485) 521-2687','1993-07-09','Air Control/Anti-Air Warfare Officer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 35,'Ollie','Turnbull','ollie.turnbull@sicewap.org','(835) 620-3330','1945-03-05','General Superintendent')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 36,'Jerry','Hopkins','jerry.hopkins@fo.mh','(211) 851-5960','2015-03-30','Child Protective Services Social Worker')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 37,'Nora','Lyons','nora.lyons@gegijap.na','(811) 311-5257','1946-01-11','Lens Grinder and Polisher')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 38,'Anne','Weiß','anne.weiß@kuvesa.pe','(843) 836-3759','1941-07-30','Civil Engineering Professor')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 39,'Louise','Gauthier','louise.gauthier@lapahu.mt','(913) 235-1856','1930-11-09','Mobile Home Servicer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 40,'Lloyd','Fani','lloyd.fani@zev.ru','(467) 487-7239','1992-10-13','Floor Refinisher')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 41,'Maud','Dunn','maud.dunn@nabeaga.ni','(724) 340-3634','1956-01-05','Senior Sales Associate')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 42,'Henry','Gigli','henry.gigli@kaot.ps','(413) 229-8428','1989-03-09','Tile Designer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 43,'Virgie','Werner','virgie.werner@tawuctuj.cf','(886) 292-9749','1942-04-18','Econometrics Professor')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 44,'Gregory','Cozzi','gregory.cozzi@eh.ru','(418) 472-1239','1995-02-09','Basketball Player')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 45,'Lucinda','Gil','lucinda.gil@fajjusuz.kr','(961) 233-3461','1935-01-31','Indirect Fire Infantryman')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 46,'Gertrude','Verbeek','gertrude.verbeek@pave.cc','(605) 226-4037','1965-02-13','Licensed Esthetician')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 47,'Mattie','Graham','mattie.graham@ispaviw.gt','(719) 765-1705','1957-12-12','Antisubmarine Warfare Intelligence Officer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 48,'Bryan','Shaw','bryan.shaw@ha.ee','(232) 228-5539','2019-08-08','Research Assistant')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 49,'Essie','Adams','essie.adams@iliat.cw','(768) 554-8377','1959-02-17','Cigar Roller')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 50,'Gary','Osborne','gary.osborne@do.ga','(311) 731-7079','2009-12-06','Customer Support Representative')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 51,'Richard','Silva','richard.silva@wi.lc','(207) 554-6244','2015-07-18','Programmer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 52,'Dustin','Pestelli','dustin.pestelli@iwage.la','(558) 913-2855','1978-11-21','Global Engineering Manager')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 53,'Henrietta','Hilton','henrietta.hilton@joopoju.pn','(832) 759-6654','1944-09-14','Telegraph and Teletype Operator')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 54,'Francisco','Giordano','francisco.giordano@gojawu.tn','(482) 736-8079','1989-02-21','Hairpiece Stylist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 55,'Cynthia','Sardi','cynthia.sardi@afigoh.mm','(677) 345-2680','1974-08-12','Tobacco Buyer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 56,'Lula','Testi','lula.testi@benom.tj','(610) 374-7581','1972-06-08','Marine Steamfitter')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 57,'Bess','Lucas','bess.lucas@jevakbe.cd','(982) 583-8067','1929-11-17','Attending Anesthesiologist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 58,'Linnie','Driessen','linnie.driessen@darhow.tr','(680) 266-3167','1968-08-17','Certified Indoor Environmentalist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 59,'Eva','Tesi','eva.tesi@dupid.cf','(611) 955-4652','1972-06-29','Land Management Forester')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 60,'Augusta','Sakai','augusta.sakai@comouc.ee','(940) 714-8088','1937-04-06','Digital Proofing and Platemaker')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 61,'Mathilda','Schwarz','mathilda.schwarz@igunisi.ao','(868) 481-5125','1942-07-31','Public Health Veterinarian')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 62,'Joe','Riley','joe.riley@pe.vu','(225) 395-2772','2018-01-08','Statement Processor')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 63,'Leon','McGee','leon.mcgee@puk.se','(365) 837-6888','2011-10-25','Computer Applications Developer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 64,'Florence','Viviani','florence.viviani@vegub.no','(606) 352-8734','1970-08-17','African History Professor')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 65,'Lee','Miceli','lee.miceli@rucwi.pf','(555) 800-7339','1982-11-20','Gastroenterology Professor')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 66,'Celia','Sodi','celia.sodi@agijit.iq','(657) 357-3671','1973-09-12','Laboratory Animal Caretaker')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 67,'Aaron','Misuri','aaron.misuri@loolu.lu','(523) 789-5485','1982-08-14','Water Pump Installer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 68,'Fanny','Parkinson','fanny.parkinson@tupwovali.cw','(766) 966-7387','1950-05-26','Orthopedic Cast Specialist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 69,'Phoebe','Vitale','phoebe.vitale@hidge.fo','(672) 613-2954','1970-09-26','Budget Coordinator')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 70,'Edith','Brennan','edith.brennan@liowci.ir','(803) 549-9387','1949-03-07','Railroad Engineer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 71,'Jeremy','Marilli','jeremy.marilli@vesa.pf','(526) 435-1819','1984-09-09','Chief Projectionist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 72,'Kathryn','Huet','kathryn.huet@wupikdoh.by','(937) 855-5936','1928-02-27','Telecasting Engineer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 73,'Lelia','Matsuo','lelia.matsuo@dajsiphaj.az','(960) 335-6192','1936-03-09','Drama Therapist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 74,'Virginia','Woods','virginia.woods@soofpe.ht','(735) 809-2611','1955-12-16','General Superintendent')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 75,'Sally','Aoki','sally.aoki@aruzusjas.tc','(857) 797-7918','1938-02-16','Technical Communicator')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 76,'Isabelle','de Ridder','isabelle.deridder@ufeco.in','(659) 331-1543','1963-12-03','Leisure Studies Professor')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 77,'Rosie','Murphy','rosie.murphy@uneehi.id','(759) 639-8597','1959-06-05','Air Conditioning Service Technician')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 78,'Lou','Meyer','lou.meyer@hahinaba.gm','(942) 352-4854','1930-02-28','Business Unit Manager')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 79,'Rodney','Love','rodney.love@zun.ph','(247) 867-8287','2013-06-24','Job Estimator')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 80,'Kenneth','Bianchini','kenneth.bianchini@jo.ws','(302) 793-9936','2002-06-16','Correctional Officer Sergeant')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 81,'Essie','Dietrich','essie.dietrich@goltuefo.mn','(861) 740-6628','1940-02-16','Parking Meter Collector')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 82,'Leila','Simon','leila.simon@lupuwuzo.gw','(953) 866-9992','1931-11-13','Signals Intelligence/Electronic Warfare Chief')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 83,'Eva','Pierre','eva.pierre@reduzris.ee','(915) 491-8384','1928-11-24','Clinical Psychiatrist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 84,'Landon','Moretti','landon.moretti@pubsav.sk','(584) 909-6235','1982-02-27','Wildlife Officer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 85,'Mittie','Sardi','mittie.sardi@lullip.nf','(673) 849-4256','1974-08-07','Food Chemist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 86,'Corey','McDaniel','corey.mcdaniel@aba.tc','(268) 208-9643','2013-10-11','Advanced Foreign Counterintelligence Specialist (Afcs)')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 87,'Hester','Stein','hester.stein@kettujwo.eu','(873) 489-6641','1940-08-03','Forest Fire Officer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 88,'Danny','Lowe','danny.lowe@ju.sd','(243) 974-5539','2014-11-16','Catalogue Illustrator')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 89,'Lillie','Winter','lillie.winter@vioburez.vi','(816) 699-1291','1946-10-11','Knife Grinder')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 90,'Brandon','Borchi','brandon.borchi@ig.al','(319) 401-1090','2001-08-02','Neuropsychiatrist')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 91,'Isaac','Bernardi','isaac.bernardi@omu.bj','(359) 691-6408','2003-01-13','Bottle Packer')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 92,'Clyde','Crawford','clyde.crawford@luw.dz','(273) 892-4646','2020-01-16','Special Education Kindergarten Teacher')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 93,'Paul','Sherman','paul.sherman@pi.cf','(304) 610-2881','2009-06-24','Commercial Art Instructor')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 94,'Craig','Russell','craig.russell@zu.nz','(237) 969-2900','2021-04-21','Ferryboat Captain')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 95,'John','Sutton','john.sutton@ag.ee','(207) 424-6468','2014-07-03','School Social Worker')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 96,'Francisco','Formigli','francisco.formigli@fopav.tn','(481) 661-8179','1991-06-17','Joint Terminal Attack Controller')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 97,'Gary','Baker','gary.baker@ji.cf','(212) 510-3444','2023-07-07','VP Sales')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 98,'Earl','Giovannoni','earl.giovannoni@lojet.ge','(433) 862-3076','1988-11-14','Auto Service Station Attendant')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 99,'Helen','Zanieri','helen.zanieri@ukve.tn','(619) 506-4452','1970-03-29','Healthcare Social Worker')
insert into alumno(version, id,nombre,apellido,correo,telefono,fecha_nacimiento,carrera) values (1, 100,'Agnes','Toccafondi','agnes.toccafondi@viipo.ae','(616) 688-6883','1972-04-17','Comedian')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 1,'1395 Jigror Park','67242','Wekviwik','Ohio','70')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 2,'216 Zunnij Grove','16795','Wosilleg','Colorado','11')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 3,'1016 Capfad View','59016','Ucaedaut','Missouri','51')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 4,'214 Decde River','19120','Uddako','Colorado','11')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 5,'1050 Bivo Way','50051','Canvorac','Montana','53')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 6,'1734 Judbi Grove','88281','Igulahep','Utah','87')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 7,'1143 Joraf Way','54266','Peprafome','New Hampshire','58')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 8,'287 Kemdol Street','19335','Ohruzi','Delaware','15')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 9,'1302 Odeter Circle','67913','Zudsova','North Carolina','66')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 10,'1563 Lisoh Square','70348','Ceksohuje','Rhode Island','79')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 11,'842 Duod Lane','43191','Ladudnu','Massachusetts','42')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 12,'1624 Nowuf Plaza','82466','Gipwufpus','South Dakota','82')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 13,'1325 Kagu Loop','61311','Dedguza','North Carolina','67')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 14,'310 Feffo Grove','19122','Odgave','Delaware','16')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 15,'1888 Derwo Park','95026','Pahlosgi','West Virginia','95')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 16,'1500 Wehovu Boulevard','78723','Aresueba','Pennsylvania','75')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 17,'984 Zamum Drive','41719','Gookpaf','Missouri','50')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 18,'1497 Dune Parkway','71190','Gawnebuh','Pennsylvania','75')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 19,'1836 Repi Terrace','93520','Lihpiwid','Virginia','92')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 20,'1805 Razup Extension','93516','Lidzuppa','Virginia','91')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 21,'1477 Kulmen Junction','77394','Zewekse','Oregon','74')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 22,'191 Ibca View','03804','Lunaor','California','10')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 23,'569 Baaci Place','21005','Faromo','Indiana','29')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 24,'999 Tohhij Pass','46672','Vojogkiw','Missouri','50')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 25,'736 Tuvo Road','31690','Goborofu','Louisiana','37')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 26,'1153 Foga Turnpike','51161','Fapgasun','New Hampshire','58')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 27,'1764 Uswuz Trail','81978','Fuswuzzub','Utah','89')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 28,'1818 Hivwe Point','99258','Oginojrip','Virginia','91')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 29,'1541 Gugu Heights','71193','Gazgusu','Rhode Island','77')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 30,'1898 Zede Point','93730','Jojdekak','West Virginia','95')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 31,'299 Ralcul Place','16514','Vipiul','Delaware','15')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 32,'1018 Turuhu Court','56696','Towezedup','Missouri','51')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 33,'1307 Omjo Highway','63951','Lumjoda','North Carolina','66')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 34,'630 Riggi Park','39542','Injari','Iowa','32')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 35,'1596 Sice Trail','74552','Mincewap','South Carolina','80')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 36,'197 Fodin River','02175','Gasamzit','California','10')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 37,'1579 Gegi Square','72121','Haggijap','South Carolina','79')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 38,'1668 Kuve Park','84383','Netvesa','Tennessee','84')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 39,'1882 Lapa Boulevard','91303','Febpahu','Washington','95')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 40,'645 Zevvat Pass','37738','Zoisdom','Kansas','33')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 41,'1380 Nabe Terrace','62414','Jifbeaga','Ohio','69')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 42,'717 Kaot Ridge','31302','Gejuwij','Louisiana','36')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 43,'1654 Tawuc View','89609','Upajuctuj','Tennessee','83')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 44,'599 Ehgad Road','21837','Fuzefo','Iowa','30')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 45,'1798 Fajju View','87113','Zacleunu','Vermont','90')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 46,'1198 Pave Extension','50502','Dicveed','New Jersey','60')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 47,'1341 Ispav Mill','61976','Duspaviw','North Dakota','67')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 48,'110 Haam Grove','03202','Kejuhib','Arizona','6')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 49,'1317 Iliat Glen','66845','Vulmutma','North Carolina','66')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 50,'303 Dogo Road','11163','Dakartov','Delaware','15')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 51,'191 Wipir Pike','00745','Borivon','California','10')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 52,'923 Iwage Parkway','46891','Tugefpe','Minnesota','47')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 53,'1605 Joopo Avenue','84265','Mepopoju','South Carolina','81')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 54,'718 Gojawu Trail','39273','Ofkotiwu','Louisiana','36')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 55,'1008 Afigoh Path','57714','Atarajip','Missouri','51')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 56,'1052 Benom Terrace','51027','Fagnomezi','Montana','53')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 57,'1902 Jevak Lane','99238','Ihelokbe','West Virginia','96')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 58,'1128 Darhow Trail','59006','Ucatetilo','Nevada','57')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 59,'1050 Dupid Extension','51195','Fawpidba','Montana','53')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 60,'1754 Como Manor','84061','Narmouc','Utah','88')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 61,'1648 Iguni Drive','87828','Wugfinsi','South Dakota','83')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 62,'141 Pepal Lane','02529','Jiumne','Arkansas','7')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 63,'265 Pukvoh Point','17583','Zimopjof','Connecticut','14')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 64,'1088 Vegub Plaza','50625','Cofgubgok','Nebraska','55')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 65,'843 Rucwi Point','45580','Sicarwit','Massachusetts','43')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 66,'1026 Agijit Manor','56725','Sogzeknew','Montana','52')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 67,'848 Loolu Pass','42368','Heewirar','Massachusetts','43')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 68,'1492 Tupwov Path','77696','Wowvossul','Pennsylvania','75')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 69,'1086 Hidge Highway','58251','Egikeki','Nebraska','55')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 70,'1516 Liow Boulevard','71344','Delowci','Pennsylvania','76')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 71,'807 Vesa Point','42633','Jomiwu','Maryland','41')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 72,'1936 Wupik Plaza','94785','Motpikdoh','Wisconsin','97')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 73,'1776 Dajsip Terrace','87013','Zadpitu','Vermont','89')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 74,'1381 Soof Avenue','63570','Mitofpe','Ohio','69')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 75,'1737 Aruzus Plaza','86779','Vorwowvec','Utah','87')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 76,'1222 Ufeco Manor','66923','Vufgamil','New Mexico','61')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 77,'1311 Uneehi Loop','65963','Sunuvni','North Carolina','66')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 78,'1896 Hahin River','94215','Pedhinaba','West Virginia','95')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 79,'232 Zunago Street','15786','Rototwu','Colorado','12')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 80,'452 Joluk Way','20269','Ceujuuh','Hawaii','23')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 81,'1697 Goltu View','86174','Varcouve','Texas','85')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 82,'1862 Lupuwu Junction','96386','Vetsuwkop','Washington','94')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 83,'1921 Reduz Turnpike','91539','Fihduzris','West Virginia','97')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 84,'857 Pubsav Square','49490','Ulcunit','Massachusetts','43')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 85,'1008 Lullip Place','58384','Ejuojtom','Missouri','51')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 86,'226 Abaudu Center','17800','Wucuduc','Colorado','12')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 87,'1688 Kettuj Loop','88338','Ijeopumo','Texas','85')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 88,'204 Junib Circle','04387','Nealidi','Colorado','10')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 89,'1564 Viobu Way','71659','Fonoburez','Rhode Island','79')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 90,'469 Igfa Parkway','21920','Fucare','Hawaii','24')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 91,'440 Omuse River','25959','Suodozu','Hawaii','22')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 92,'101 Luwmo Heights','08389','Ejigihoc','Arizona','5')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 93,'312 Pice Ridge','10451','Cigafhec','Delaware','16')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 94,'76 Zuufa Grove','04796','Movufhe','Alaska','4')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 95,'211 Agmo Circle','10722','Bojidis','Colorado','11')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 96,'672 Fopav Trail','39166','Odvatije','Kentucky','34')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 97,'31 Jibe Ridge','01241','Degawu','Alabama','2')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 98,'723 Lojet Junction','34376','Netegkir','Louisiana','37')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 99,'1095 Ukve Trail','51940','Fukveura','Nebraska','55')
insert into asignatura(version, id,nombre,catedratico,horario,modalidad,precio) values (1, 100,'1054 Viipo Boulevard','52658','Gomipova','Montana','53')
